<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $districts = [
            ['id' => 1, 'nom_district' => 'Ambohidratrimo', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 2, 'nom_district' => 'Andramasina', 'id_region' => 1, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 3, 'nom_district' => 'Anjozorobe', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 4, 'nom_district' => 'Ankazobe', 'id_region' => 1, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 5, 'nom_district' => 'Atsimondrano', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 6, 'nom_district' => 'Avaradrano', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 7, 'nom_district' => 'Antananarivo-Ville', 'id_region' => 1, 'edilitaire' => 1000, 'agricole' => 1000],
            ['id' => 8, 'nom_district' => 'Manjakandriana', 'id_region' => 1, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 9, 'nom_district' => 'Fenoarivobe', 'id_region' => 2, 'edilitaire' => null, 'agricole' => null],
            ['id' => 10, 'nom_district' => 'Tsiroanomandidy', 'id_region' => 2, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 11, 'nom_district' => 'Arivonimamo', 'id_region' => 3, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 12, 'nom_district' => 'Miarinarivo', 'id_region' => 3, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 13, 'nom_district' => 'Soavinandirana', 'id_region' => 3, 'edilitaire' => null, 'agricole' => null],
            ['id' => 14, 'nom_district' => 'Ambatolampy', 'id_region' => 4, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 15, 'nom_district' => 'Antanifotsy', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 16, 'nom_district' => 'Antsirabe I', 'id_region' => 4, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 17, 'nom_district' => 'Antsirabe II', 'id_region' => 4, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 18, 'nom_district' => 'Betafo', 'id_region' => 4, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 19, 'nom_district' => 'Faratsiho', 'id_region' => 4, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 20, 'nom_district' => 'Mandoto', 'id_region' => 4, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 21, 'nom_district' => 'Ambanja', 'id_region' => 22, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 22, 'nom_district' => 'Ambilobe', 'id_region' => 22, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 23, 'nom_district' => 'Antsiranana I', 'id_region' => 22, 'edilitaire' => 50, 'agricole' => 50],
            ['id' => 24, 'nom_district' => 'Antsiranana II', 'id_region' => 22, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 25, 'nom_district' => 'Nosy-BE', 'id_region' => 22, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 26, 'nom_district' => 'Andapa', 'id_region' => 23, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 27, 'nom_district' => 'Antalaha', 'id_region' => 23, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 28, 'nom_district' => 'Sambava', 'id_region' => 23, 'edilitaire' => 50, 'agricole' => 50],
            ['id' => 29, 'nom_district' => 'Vohemar', 'id_region' => 23, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 30, 'nom_district' => 'Ambatofinandrahana', 'id_region' => 5, 'edilitaire' => null, 'agricole' => null],
            ['id' => 31, 'nom_district' => 'Ambositra', 'id_region' => 5, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 32, 'nom_district' => 'Fandriana', 'id_region' => 5, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 33, 'nom_district' => 'Manandriana', 'id_region' => 5, 'edilitaire' => null, 'agricole' => null],
            ['id' => 34, 'nom_district' => 'Befotaka Atsimo', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 35, 'nom_district' => 'Farafangana', 'id_region' => 6, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 36, 'nom_district' => 'Midongy Sud', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 37, 'nom_district' => 'Vangaindrano', 'id_region' => 6, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 38, 'nom_district' => 'Vondrozo', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 39, 'nom_district' => 'Ambalavao', 'id_region' => 7, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 40, 'nom_district' => 'Ambohimahasoa', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 41, 'nom_district' => 'Fianarantsoa', 'id_region' => 7, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 42, 'nom_district' => 'Isandra', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 43, 'nom_district' => 'Ikalamavony', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 44, 'nom_district' => 'Vohibato', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 45, 'nom_district' => 'Lalangina', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 46, 'nom_district' => 'Iakora', 'id_region' => 10, 'edilitaire' => null, 'agricole' => null],
            ['id' => 47, 'nom_district' => 'Ihosy', 'id_region' => 10, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 48, 'nom_district' => 'Ivohibe', 'id_region' => 10, 'edilitaire' => null, 'agricole' => null],
            ['id' => 49, 'nom_district' => 'Ifanadiana', 'id_region' => 9, 'edilitaire' => null, 'agricole' => null],
            ['id' => 50, 'nom_district' => 'Mananjary', 'id_region' => 9, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 51, 'nom_district' => 'Nosy Varika', 'id_region' => 9, 'edilitaire' => null, 'agricole' => null],
            ['id' => 52, 'nom_district' => 'Ikongo', 'id_region' => 8, 'edilitaire' => null, 'agricole' => null],
            ['id' => 53, 'nom_district' => 'Manakara', 'id_region' => 8, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 54, 'nom_district' => 'Vohipeno', 'id_region' => 8, 'edilitaire' => null, 'agricole' => null],
            ['id' => 55, 'nom_district' => 'Kandreho', 'id_region' => 14, 'edilitaire' => null, 'agricole' => null],
            ['id' => 56, 'nom_district' => 'Maevatanana', 'id_region' => 14, 'edilitaire' => null, 'agricole' => null],
            ['id' => 57, 'nom_district' => 'Tsaratanana', 'id_region' => 14, 'edilitaire' => null, 'agricole' => null],
            ['id' => 58, 'nom_district' => 'Amabato Boeni', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 59, 'nom_district' => 'Mahajanga I', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 60, 'nom_district' => 'Mahajanga II', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 61, 'nom_district' => 'Marovoay', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 62, 'nom_district' => 'Mitsinjo', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 63, 'nom_district' => 'Soalala', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 64, 'nom_district' => 'Ambatomainty', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 65, 'nom_district' => 'Antsalova', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 66, 'nom_district' => 'Besalampy', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 67, 'nom_district' => 'Maintirano', 'id_region' => 16, 'edilitaire' => 5, 'agricole' => 2],
            ['id' => 68, 'nom_district' => 'Morafenobe', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 69, 'nom_district' => 'Analalava', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 70, 'nom_district' => 'Antsohihy', 'id_region' => 17, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 71, 'nom_district' => 'Bealalana', 'id_region' => 17, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 72, 'nom_district' => 'Befandriana Nord', 'id_region' => 17, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 73, 'nom_district' => 'Mampikony', 'id_region' => 17, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 74, 'nom_district' => 'Mandritsara', 'id_region' => 17, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 75, 'nom_district' => 'Port-Berge', 'id_region' => 17, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 76, 'nom_district' => 'Ambatondrazaka', 'id_region' => 11, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 77, 'nom_district' => 'Amparafaravola', 'id_region' => 11, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 78, 'nom_district' => 'Andilamena', 'id_region' => 11, 'edilitaire' => null, 'agricole' => null],
            ['id' => 79, 'nom_district' => 'Anosibe An\'Ala', 'id_region' => 11, 'edilitaire' => null, 'agricole' => null],
            ['id' => 80, 'nom_district' => 'Moramanga', 'id_region' => 11, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 81, 'nom_district' => 'Fenerive Est', 'id_region' => 12, 'edilitaire' => 50, 'agricole' => 7],
            ['id' => 82, 'nom_district' => 'Mananara-Nord', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 83, 'nom_district' => 'Maroantsetra', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 84, 'nom_district' => 'Sainte Marie', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 85, 'nom_district' => 'Soanierana Ivongo', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 86, 'nom_district' => 'Vavatenina', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 87, 'nom_district' => 'Antanambao Manampontsy', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 88, 'nom_district' => 'Brickaville', 'id_region' => 13, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 89, 'nom_district' => 'Mahanoro', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 90, 'nom_district' => 'Marolambo', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 91, 'nom_district' => 'Toamasina I', 'id_region' => 13, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 92, 'nom_district' => 'Toamasina II', 'id_region' => 13, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 93, 'nom_district' => 'Vatomandry', 'id_region' => 13, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 94, 'nom_district' => 'Ambovombe Androy', 'id_region' => 18, 'edilitaire' => 5, 'agricole' => 2],
            ['id' => 95, 'nom_district' => 'Bekily', 'id_region' => 18, 'edilitaire' => null, 'agricole' => null],
            ['id' => 96, 'nom_district' => 'Beloha Androy', 'id_region' => 18, 'edilitaire' => null, 'agricole' => null],
            ['id' => 97, 'nom_district' => 'Tsihombe', 'id_region' => 18, 'edilitaire' => null, 'agricole' => null],
            ['id' => 98, 'nom_district' => 'Amboasary Sud', 'id_region' => 19, 'edilitaire' => null, 'agricole' => null],
            ['id' => 99, 'nom_district' => 'Betroka', 'id_region' => 19, 'edilitaire' => null, 'agricole' => null],
            ['id' => 100, 'nom_district' => 'Taolanaro', 'id_region' => 19, 'edilitaire' => null, 'agricole' => null],
            ['id' => 101, 'nom_district' => 'Ampanihy Ouest', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 102, 'nom_district' => 'Ankazoabo Sud', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 103, 'nom_district' => 'Benenitra', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 104, 'nom_district' => 'Beroroha', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 105, 'nom_district' => 'Betioky Sud', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 106, 'nom_district' => 'Morombe', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 107, 'nom_district' => 'Sakaraha', 'id_region' => 20, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 108, 'nom_district' => 'Toliara I', 'id_region' => 20, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 109, 'nom_district' => 'Toliara II', 'id_region' => 20, 'edilitaire' => 50, 'agricole' => 5],
            ['id' => 110, 'nom_district' => 'Belo Sur Tsiribihina', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null],
            ['id' => 111, 'nom_district' => 'Mahabo', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null],
            ['id' => 112, 'nom_district' => 'Manja', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null],
            ['id' => 113, 'nom_district' => 'Miandrivazo', 'id_region' => 21, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 114, 'nom_district' => 'Morondava', 'id_region' => 21, 'edilitaire' => 50, 'agricole' => 5]
        ];
        DB::table('districts')->insert($districts);
    }
}
