<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $districts = [
            ['id' => 1, 'nom_district' => 'AMBOHIDRATRIMO', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 2, 'nom_district' => 'ANDRAMASINA', 'id_region' => 1, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 3, 'nom_district' => 'ANJOZOROBE', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 4, 'nom_district' => 'ANKAZOBE', 'id_region' => 1, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 5, 'nom_district' => 'ATSIMONDRANO', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 6, 'nom_district' => 'AVARADRANO', 'id_region' => 1, 'edilitaire' => 20, 'agricole' => 10],
            ['id' => 7, 'nom_district' => 'RENIVOHITRA', 'id_region' => 1, 'edilitaire' => 1000, 'agricole' => 1000],
            ['id' => 8, 'nom_district' => 'MANJAKANDRIANA', 'id_region' => 1, 'edilitaire' => 10, 'agricole' => 5],
            ['id' => 9, 'nom_district' => 'FENOARIVOBE', 'id_region' => 2, 'edilitaire' => null, 'agricole' => null],
            ['id' => 10, 'nom_district' => 'TSIROANOMANDIDY', 'id_region' => 2, 'edilitaire' => null, 'agricole' => null],
            ['id' => 11, 'nom_district' => 'ARIVONIMAMO', 'id_region' => 3, 'edilitaire' => null, 'agricole' => null],
            ['id' => 12, 'nom_district' => 'MIARINARIVO', 'id_region' => 3, 'edilitaire' => null, 'agricole' => null],
            ['id' => 13, 'nom_district' => 'SOAVINANDRIANA', 'id_region' => 3, 'edilitaire' => null, 'agricole' => null],
            ['id' => 14, 'nom_district' => 'AMBATOLAMPY', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 15, 'nom_district' => 'ANTANIFOTSY', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 16, 'nom_district' => 'ANTSIRABE I', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 17, 'nom_district' => 'ANTSIRABE II', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 18, 'nom_district' => 'BETAFO', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 19, 'nom_district' => 'FARATSIHO', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 20, 'nom_district' => 'MANDOTO', 'id_region' => 4, 'edilitaire' => null, 'agricole' => null],
            ['id' => 21, 'nom_district' => 'AMBANJA', 'id_region' => 22, 'edilitaire' => null, 'agricole' => null],
            ['id' => 22, 'nom_district' => 'AMBILOBE', 'id_region' => 22, 'edilitaire' => null, 'agricole' => null],
            ['id' => 23, 'nom_district' => 'ANTSIRANANA I', 'id_region' => 22, 'edilitaire' => null, 'agricole' => null],
            ['id' => 24, 'nom_district' => 'ANTSIRANANA II', 'id_region' => 22, 'edilitaire' => null, 'agricole' => null],
            ['id' => 25, 'nom_district' => 'NOSY-BE', 'id_region' => 22, 'edilitaire' => null, 'agricole' => null],
            ['id' => 26, 'nom_district' => 'ANDAPA', 'id_region' => 23, 'edilitaire' => null, 'agricole' => null],
            ['id' => 27, 'nom_district' => 'ANTALAHA', 'id_region' => 23, 'edilitaire' => null, 'agricole' => null],
            ['id' => 28, 'nom_district' => 'SAMBAVA', 'id_region' => 23, 'edilitaire' => null, 'agricole' => null],
            ['id' => 29, 'nom_district' => 'VOHEMAR', 'id_region' => 23, 'edilitaire' => null, 'agricole' => null],
            ['id' => 30, 'nom_district' => 'AMBATOFINANDRAHANA', 'id_region' => 5, 'edilitaire' => null, 'agricole' => null],
            ['id' => 31, 'nom_district' => 'AMBOSITRA', 'id_region' => 5, 'edilitaire' => null, 'agricole' => null],
            ['id' => 32, 'nom_district' => 'FANDRIANA', 'id_region' => 5, 'edilitaire' => null, 'agricole' => null],
            ['id' => 33, 'nom_district' => 'MANANDRIANA', 'id_region' => 5, 'edilitaire' => null, 'agricole' => null],
            ['id' => 34, 'nom_district' => 'BEFOTAKA ATSIMO', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 35, 'nom_district' => 'FARAFANGANA', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 36, 'nom_district' => 'MIDONGY SUD', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 37, 'nom_district' => 'VANGAINDRANO', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 38, 'nom_district' => 'VONDROZO', 'id_region' => 6, 'edilitaire' => null, 'agricole' => null],
            ['id' => 39, 'nom_district' => 'AMBALAVAO', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 40, 'nom_district' => 'AMBOHIMAHASOA', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 41, 'nom_district' => 'FIANARANTSOA', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 42, 'nom_district' => 'ISANDRA', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 43, 'nom_district' => 'IKALAMAVONY', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 44, 'nom_district' => 'VOHIBATO', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 45, 'nom_district' => 'LALANGINA', 'id_region' => 7, 'edilitaire' => null, 'agricole' => null],
            ['id' => 46, 'nom_district' => 'IAKORA', 'id_region' => 10, 'edilitaire' => null, 'agricole' => null],
            ['id' => 47, 'nom_district' => 'IHOSY', 'id_region' => 10, 'edilitaire' => null, 'agricole' => null],
            ['id' => 48, 'nom_district' => 'IVOHIBE', 'id_region' => 10, 'edilitaire' => null, 'agricole' => null],
            ['id' => 49, 'nom_district' => 'IFANADIANA', 'id_region' => 9, 'edilitaire' => null, 'agricole' => null],
            ['id' => 50, 'nom_district' => 'MANANJARY', 'id_region' => 9, 'edilitaire' => null, 'agricole' => null],
            ['id' => 51, 'nom_district' => 'NOSY VARIKA', 'id_region' => 9, 'edilitaire' => null, 'agricole' => null],
            ['id' => 52, 'nom_district' => 'IKONGO', 'id_region' => 8, 'edilitaire' => null, 'agricole' => null],
            ['id' => 53, 'nom_district' => 'MANAKARA', 'id_region' => 8, 'edilitaire' => null, 'agricole' => null],
            ['id' => 54, 'nom_district' => 'VOHIPENO', 'id_region' => 8, 'edilitaire' => null, 'agricole' => null],
            ['id' => 55, 'nom_district' => 'KANDREHO', 'id_region' => 14, 'edilitaire' => null, 'agricole' => null],
            ['id' => 56, 'nom_district' => 'MAEVATANANA', 'id_region' => 14, 'edilitaire' => null, 'agricole' => null],
            ['id' => 57, 'nom_district' => 'TSARATANANA', 'id_region' => 14, 'edilitaire' => null, 'agricole' => null],
            ['id' => 58, 'nom_district' => 'AMBATO BOENI', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 59, 'nom_district' => 'MAHAJANGA I', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 60, 'nom_district' => 'MAHAJANGA II', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 61, 'nom_district' => 'MAROVOAY', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 62, 'nom_district' => 'MITSINJO', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 63, 'nom_district' => 'SOALALA', 'id_region' => 15, 'edilitaire' => null, 'agricole' => null],
            ['id' => 64, 'nom_district' => 'AMBATOMAINTY', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 65, 'nom_district' => 'ANTSALOVA', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 66, 'nom_district' => 'BESALAMPY', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 67, 'nom_district' => 'MAINTIRANO', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 68, 'nom_district' => 'MORAFENOBE', 'id_region' => 16, 'edilitaire' => null, 'agricole' => null],
            ['id' => 69, 'nom_district' => 'ANALALAVA', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 70, 'nom_district' => 'ANTSOHIHY', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 71, 'nom_district' => 'BEALANANA', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 72, 'nom_district' => 'BEFANDRIANA NORD', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 73, 'nom_district' => 'MAMPIKONY', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 74, 'nom_district' => 'MANDRITSARA', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 75, 'nom_district' => 'PORT-BERGE', 'id_region' => 17, 'edilitaire' => null, 'agricole' => null],
            ['id' => 76, 'nom_district' => 'AMBATONDRAZAKA', 'id_region' => 11, 'edilitaire' => null, 'agricole' => null],
            ['id' => 77, 'nom_district' => 'AMPARAFARAVOLA', 'id_region' => 11, 'edilitaire' => null, 'agricole' => null],
            ['id' => 78, 'nom_district' => 'ANDILAMENA', 'id_region' => 11, 'edilitaire' => null, 'agricole' => null],
            ['id' => 79, 'nom_district' => 'ANOSIBE AN\'ALA', 'id_region' => 11, 'edilitaire' => null, 'agricole' => null],
            ['id' => 80, 'nom_district' => 'MORAMANGA', 'id_region' => 11, 'edilitaire' => null, 'agricole' => null],
            ['id' => 81, 'nom_district' => 'FENERIVE EST', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 82, 'nom_district' => 'MANANARA-NORD', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 83, 'nom_district' => 'MAROANTSETRA', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 84, 'nom_district' => 'SAINTE MARIE', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 85, 'nom_district' => 'SOANIERANA IVONGO', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 86, 'nom_district' => 'VAVATENINA', 'id_region' => 12, 'edilitaire' => null, 'agricole' => null],
            ['id' => 87, 'nom_district' => 'ANTANAMBAO MANAMPONTSY', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 88, 'nom_district' => 'BRICKAVILLE', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 89, 'nom_district' => 'MAHANORO', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 90, 'nom_district' => 'MAROLAMBO', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 91, 'nom_district' => 'TOAMASINA I', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 92, 'nom_district' => 'TOAMASINA II', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 93, 'nom_district' => 'VATOMANDRY', 'id_region' => 13, 'edilitaire' => null, 'agricole' => null],
            ['id' => 94, 'nom_district' => 'AMBOVOMBE ANDROY', 'id_region' => 18, 'edilitaire' => null, 'agricole' => null],
            ['id' => 95, 'nom_district' => 'BEKILY', 'id_region' => 18, 'edilitaire' => null, 'agricole' => null],
            ['id' => 96, 'nom_district' => 'BELOHA ANDROY', 'id_region' => 18, 'edilitaire' => null, 'agricole' => null],
            ['id' => 97, 'nom_district' => 'TSIHOMBE', 'id_region' => 18, 'edilitaire' => null, 'agricole' => null],
            ['id' => 98, 'nom_district' => 'AMBOASARY SUD', 'id_region' => 19, 'edilitaire' => null, 'agricole' => null],
            ['id' => 99, 'nom_district' => 'BETROKA', 'id_region' => 19, 'edilitaire' => null, 'agricole' => null],
            ['id' => 100, 'nom_district' => 'TAOLANARO', 'id_region' => 19, 'edilitaire' => null, 'agricole' => null],
            ['id' => 101, 'nom_district' => 'AMPANIHY OUEST', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 102, 'nom_district' => 'ANKAZOABO SUD', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 103, 'nom_district' => 'BENENITRA', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 104, 'nom_district' => 'BEROROHA', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 105, 'nom_district' => 'BETIOKY SUD', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 106, 'nom_district' => 'MOROMBE', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 107, 'nom_district' => 'SAKARAHA', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 108, 'nom_district' => 'TOLIARA I', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 109, 'nom_district' => 'TOLIARA II', 'id_region' => 20, 'edilitaire' => null, 'agricole' => null],
            ['id' => 110, 'nom_district' => 'BELO SUR TSIRIBIHINA', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null],
            ['id' => 111, 'nom_district' => 'MAHABO', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null],
            ['id' => 112, 'nom_district' => 'MANJA', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null],
            ['id' => 113, 'nom_district' => 'MIANDRIVAZO', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null],
            ['id' => 114, 'nom_district' => 'MORONDAVA', 'id_region' => 21, 'edilitaire' => null, 'agricole' => null]
        ];
        DB::table('districts')->insert($districts);
    }
}
